### ISSUE TITLE
404 in readme.md

### ISSUE THREAD

**Issue by IsaacPushButton** [Sensirion/arduino-i2c-sfa3x#1]
"Click here to learn more about the SFA30 sensor and the SFA30 Evaluation Kit Board." section of the readme.md contains a link to https://www.sensirion.com/en/environmental-sensors/evaluation-kit-sek-sfa30/ which returns a 404 error.

**Comment by psachs** [comment]
Thanks for the report. Looks like the link has changed. The correct link is as follows:

https://www.sensirion.com/en/environmental-sensors/evaluation-kit-sek-environmental-sensing/evaluation-kit-sek-sfa30/

We will update it asap. @MBjoern can you look at this?

**Comment by MBjoern** [comment]
Fixed
